# Generated by Django 3.1.6 on 2021-02-08 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpaga_project_1', '0002_auto_20210208_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(blank=True, choices=[('created', 'Created'), ('paid', 'Paid'), ('delivered', 'Delivered')], max_length=80, null=True),
        ),
    ]
